version: "3.8"

services:
  backend:
    container_name: hekaz-backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: npm run dev
